theme: minima
title: Peter Bridgeman's Homepage
description: Refreshing web developer skills for deployments.

author:
  name: Peter Bridgeman
  email: "bridgeman@pobox.com"

minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/bridgeman" }
    - { platform: twitter, user_url: "https://x.com/bridgemanmedia" }
